# Generated by Django 6.0.2 on 2026-09-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_inventoryitem_product_link_alter_inventoryitem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=b'I01\n')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('item_type', models.CharField(choices=[('Meeting', 'Meeting'), ('Deal', 'Deal'), ('Task', 'Task'), ('Other', 'Other')], default='Task', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
