# Generated by Django 6.0.2 on 2026-09-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_scheduleitem_alter_inventoryitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
